server:
  port: 8080

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/learn_spring_eric?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: rppt
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.pactera.spring.boot.learn.mapper


minio:
  access-key: vbfoX8D2NuKHSGQxX2wa
  secret-key: mMaiCHNiKmP418VKfOyAmGFciSpstlEy9rkVs9D5
  endpoint: http://127.0.0.1:9000